statistics lib are also present in pandas and numpy

In [1]:
import numpy as np

In [4]:
a = np.array([[2,3,6],[7,9,4],[6,5,3],[9,8,1]])

In [5]:
a

array([[2, 3, 6],
       [7, 9, 4],
       [6, 5, 3],
       [9, 8, 1]])

In [6]:
a.shape

(4, 3)

In [7]:
#to find mean
np.mean(a)

5.25

In [8]:
a.mean()

5.25

In [9]:
# along columns
np.mean(a,0)

array([6.  , 6.25, 3.5 ])

In [10]:
#along rows
np.mean(a,1)


array([3.66666667, 6.66666667, 4.66666667, 6.        ])

In [11]:
a.mean(axis=0)

array([6.  , 6.25, 3.5 ])

In [12]:
a.mean(axis=1)

array([3.66666667, 6.66666667, 4.66666667, 6.        ])

In [15]:
#Similarily median

np.median(a)

5.5

In [17]:
b =[2,3,4,1,5,6,7,8]

In [20]:
#mean,median,mode using pandas

import pandas as pd

In [21]:
df= pd.Series(b)

In [22]:
df

0    2
1    3
2    4
3    1
4    5
5    6
6    7
7    8
dtype: int64

In [23]:
df.mean()

4.5

In [24]:
df.mode()

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [25]:
df.median()

4.5

In [26]:
#Standard deviation
np.std(df)

2.29128784747792

In [27]:
#variance
np.var(df)

5.25

In [30]:
#percentile
np.percentile(df,50)

4.5

In [31]:
np.percentile(df,30)

3.1

# Scipy

In [32]:
import scipy
import scipy.stats as st
from scipy.stats import zscore


In [33]:
zscore([43,32,56,78,32,13,45])

array([ 0.01500075, -0.56252813,  0.69753488,  1.85259263, -0.56252813,
       -1.56007801,  0.120006  ])

In [34]:
df = pd.read_csv("brainsize.csv",sep = ';',na_values = ".")

In [35]:
df

id  Gender  FSIQ  VIQ  PIQ  Weight  Height  MRI_Count
0    1  Female   133  132  124   118.0    64.5     816932
1    2    Male   140  150  124     NaN    72.5    1001121
2    3    Male   139  123  150   143.0    73.3    1038437
3    4    Male   133  129  128   172.0    68.8     965353
4    5  Female   137  132  134   147.0    65.0     951545
5    6  Female    99   90  110   146.0    69.0     928799
6    7  Female   138  136  131   138.0    64.5     991305
7    8  Female    92   90   98   175.0    66.0     854258
8    9    Male    89   93   84   134.0    66.3     904858
9   10    Male   133  114  147   172.0    68.8     955466
10  11  Female   132  129  124   118.0    64.5     833868
11  12    Male   141  150  128   151.0    70.0    1079549
12  13    Male   135  129  124   155.0    69.0     924059
13  14  Female   140  120  147   155.0    70.5     856472
14  15  Female    96  100   90   146.0    66.0     878897
15  16  Female    83   71   96   135.0    68.0     865363
16  17  Female   132  132  120   127.0    68.5     852244
17  18    Male   100   96  102   178.0    73.5     945088
18  19  Female   101  112   84   136.0    66.3     808020
19  20    Male    80   77   86   180.0    70.0     889083
20  21    Male    83   83   86     NaN     NaN     892420
21  22    Male    97  107   84   186.0    76.5     905940
22  23  Female   135  129  134   122.0    62.0     790619
23  24    Male   139  145  128   132.0    68.0     955003
24  25  Female    91   86  102   114.0    63.0     831772
25  26    Male   141  145  131   171.0    72.0     935494
26  27  Female    85   90   84   140.0    68.0     798612
27  28    Male   103   96  110   187.0    77.0    1062462
28  29  Female    77   83   72   106.0    63.0     793549
29  30  Female   130  126  124   159.0    66.5     866662
30  31  Female   133  126  132   127.0    62.5     857782
31  32    Male   144  145  137   191.0    67.0     949589
32  33    Male   103   96  110   192.0    75.5     997925
33  34    Male    90   96   86   181.0    69.0     879987
34  35  Female    83   90   81   143.0    66.5     834344
35  36  Female   133  129  128   153.0    66.5     948066
36  37    Male   140  150  124   144.0    70.5     949395
37  38  Female    88   86   94   139.0    64.5     893983
38  39    Male    81   90   74   148.0    74.0     930016
39  40    Male    89   91   89   179.0    75.5     935863

In [36]:
df.columns

Index(['id', 'Gender', 'FSIQ', 'VIQ', 'PIQ', 'Weight', 'Height', 'MRI_Count'], dtype='object')

In [37]:
df['FSIQ'].mean()

113.45

In [38]:
df['VIQ'].mean()

112.35

In [39]:
df['PIQ'].mean()

111.025

# Hypothesis Testing

In [40]:
st.ttest_1samp(df['FSIQ'],110)

Ttest_1sampResult(statistic=0.9060564460313781, pvalue=0.3704699810976697)

H0 == close to comparing value
Ha == not close to that value

Since pvalue is greater than 5 % . H0 is accepted

In [42]:
st.ttest_1samp(df['VIQ'],110)

Ttest_1sampResult(statistic=0.6293461053092635, pvalue=0.5327920500038907)

TTEST INDEPENDENT

In [44]:
st.ttest_ind(df['FSIQ'],df['PIQ'])

Ttest_indResult(statistic=0.465637596380964, pvalue=0.6427725009414841)